TRANSACTION_CONTEXT_AGENT_NAME = "Transaction Context Agent"
BEHAVIORAL_PATTERN_AGENT_NAME = "Behavioral Pattern Agent"
INTERNAL_POLICY_RAG_AGENT_NAME = "Internal Policy RAG Agent"
EXTERNAL_THREAT_INTEL_AGENT_NAME = "External Threat Intel Agent"
EVIDENCE_AGGREGATOR_AGENT_NAME = "Evidence Aggregator Agent"
DEBATE_AGENT_PRO_FRAUD_NAME = "Debate Agent (Pro-Fraud)"
DEBATE_AGENT_PRO_CUSTOMER_NAME = "Debate Agent (Pro-Customer)"
DECISION_ARBITER_AGENT_NAME = "Decision Arbiter Agent"
EXPLAINABILITY_AGENT_NAME = "Explain Agent"


MAP_AGENT_MODEL = {
    TRANSACTION_CONTEXT_AGENT_NAME: "gpt-4o-mini",
    BEHAVIORAL_PATTERN_AGENT_NAME: "gpt-4o-mini",
    INTERNAL_POLICY_RAG_AGENT_NAME: "gpt-4.1",
    EXTERNAL_THREAT_INTEL_AGENT_NAME: "gpt-4.1",
    EVIDENCE_AGGREGATOR_AGENT_NAME: "gpt-4o-mini",
    DEBATE_AGENT_PRO_FRAUD_NAME: "gpt-4o-mini",
    DEBATE_AGENT_PRO_CUSTOMER_NAME: "gpt-4o-mini",
    DECISION_ARBITER_AGENT_NAME: "gpt-4.1",
    EXPLAINABILITY_AGENT_NAME: "gpt-4o-mini",
}
